CREATE TABLE "data" (
  "data_id" SERIAL PRIMARY KEY,
  "external_site_id" VARCHAR(255) NOT NULL,
  "dvspondes" VARCHAR(255) NOT NULL,
  "file_id" INT REFERENCES "file"("file_id") ON DELETE CASCADE ON UPDATE CASCADE,
  "usubjid" VARCHAR(255),
  "dventc" VARCHAR(255),
  "dventcviz" VARCHAR(255),
  "dvsponsev" VARCHAR(255),
  "impor" INT,
  "at" TEXT,
  "at_date" TIMESTAMP,
  "domain" VARCHAR(255),
  "dvseq" INT,
  "dvref_id" INT,
  "dvendtc" VARCHAR(255),
  "dvcat_id" INT,
  "dvdecod_id" INT,
  "adv" VARCHAR(255),
  "nonadv" VARCHAR(255),
  "dvscat" VARCHAR(255),
  "dvstdtc" VARCHAR(255)
);