spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          # Specifies your Active Directory ID:
          tenant-id: [tenant-id]
        credential:  
          # Specifies your App Registration's Application ID:
          client-id: [client_id]
          # Specifies your App Registration's secret key:
          client-secret: [client_secret]
        # Specifies the post-log-out-redirect-uri, where to return your app after logout.
        post-logout-redirect-uri: http://localhost:8080
app:
  protect:
    authenticated: /, /site, /data-upload, /dashboard

# un-comment the following lines if you are deploying to a reverse proxy (e.g. Azure App Service)
# server:
#   forward-headers-strategy: native
#   tomcat:
#     remoteip:
#       protocol-header: "X-Forwarded-Proto"
#       remote-ip-header: "X-Forwarded-For"
#       internal-proxies: ".*"
