INSERT INTO
    "user_account" (
        "username",
        "role_id",
        "is_site",
        "is_sponsor",
        "date_created"
    )
VALUES
    (
        'drjohndoe@gmail.com',
        1,
        true,
        true,
        '01/01/2023'
    ),
    (
        'sara.smith.md@hospital.edu',
        1,
        true,
        false,
        '02/01/2023'
    ),
    (
        'healthpro123@hotmail.com',
        1,
        false,
        true,
        '03/01/2023'
    ),
    (
        'emily.green.md@clinic.org',
        1,
        false,
        false,
        '04/01/2023'
    ),
    (
        'clinical.expert99@medcenter.net',
        2,
        true,
        true,
        '05/01/2023'
    ),
    (
        'medresearcher23@outlook.com',
        2,
        true,
        false,
        '06/01/2023'
    ),
    (
        'doctorcare456@gmail.com',
        2,
        false,
        true,
        '07/01/2023'
    ),
    (
        'doctor.awesome@yahoo.com',
        2,
        false,
        false,
        '08/01/2023'
    );