INSERT INTO
    dvdecod_colour ("dvdecod", "colour")
VALUES
    ('OUT OF WINDOW - PK COLLECTION', '#4285F4'),
    (
        'OUT OF WINDOW - TREATMENT ADMINISTRATION',
        '#0F9D58'
    ),
    (
        'OUT OF WINDOW - BIOMARKER COLLECTION OR EXPLORATORY ASSESSMENT',
        '#F4B400'
    ),
    ('OUT OF WINDOW - EFFICACY ASSESSMENT', '#DB4437'),
    ('OUT OF WINDOW - ECG', '#3F51B5'),
    ('OUT OF WINDOW - VITAL SIGNS', '#E91E63'),
    ('OUT OF WINDOW - BLOODS LOCAL', '#9C27B0'),
    ('OUT OF WINDOW - BLOODS CENTRAL', '#673AB7'),
    ('OUT OF WINDOW - OTHER', '#3F51B5'),
    ('MISSED ASSESMENT - PK COLLECTION', '#2196F3'),
    (
        'MISSED ASSESMENT - TREATMENT ADMINISTRATION',
        '#03A9F4'
    ),
    (
        'MISSED ASSESMENT - BIOMARKER COLLECTION OR EXPLORATORY ASSESSMENT',
        '#00BCD4'
    ),
    (
        'MISSED ASSESMENT - EFFICACY ASSESSMENT',
        '#009688'
    ),
    ('MISSED ASSESMENT - ECG', '#4CAF50'),
    ('MISSED ASSESMENT- VITAL SIGNS', '#8BC34A'),
    ('MISSED ASSESMENT - BLOODS LOCAL', '#CDDC39'),
    ('MISSED ASSESMENT - BLOODS CENTRAL', '#FFEB3B'),
    ('MISSED ASSESSMENT - OTHER', '#FFC107'),
    ('ASSESSMENT NOT PROPERLY PERFORMED', '#FF9800'),
    ('ASSESSMENT PERFORMED OUT OF ORDER', '#FF5722'),
    ('INCOMPLETE ASSESSMENT', '#795548'),
    (
        'OTHER ASSESSMENT OR TIME POINT WINDOW',
        '#607D8B'
    ),
    ('ELIGIBILITY CRITERIA NOT MET', '#F44336'),
    (
        'MEDICATION, EXCLUDED BY THE PROTOCOL, WAS ADMINISTERED',
        '#E91E63'
    ),
    (
        'VACCINE, EXCLUDED BY THE PROTOCOL, WAS ADMINISTERED',
        '#9C27B0'
    ),
    (
        'DEVICE, EXCLUDED BY THE PROTOCOL, WAS ADMINISTERED',
        '#673AB7'
    ),
    (
        'OTHER EXCLUDED MEDICATION, VACCINE OR DEVICE DEVIATION',
        '#3F51B5'
    ),
    (
        'SAE NOT REPORTED WITHIN THE EXPECTED TIME FRAME',
        '#2196F3'
    ),
    ('AES OF SPECIAL INTEREST', '#03A9F4'),
    (
        'FAILURE TO CONFIRM CAUSALITY ASSESSMENT WITHIN THE EXPECTED TIME FRAME',
        '#00BCD4'
    ),
    (
        'LIVER FUNCTION ABNORMALITIES PER PROTOCOL',
        '#009688'
    ),
    ('PREGNANCY', '#4CAF50'),
    ('OTHER', '#8BC34A'),
    (
        'INFORMED CONSENT/ASSENT NOT SIGNED AND/OR DATED BY SUBJECT (PARENT/LEGAL REPRESENTATIVE, IF APPLICABLE)',
        '#CDDC39'
    ),
    (
        'INFORMED CONSENT/ASSENT NOT SIGNED AND/OR DATED BY APPROPRIATE SITE STAFF',
        '#FFEB3B'
    ),
    (
        'INFORMED CONSENT/ASSENT NOT SIGNED PRIOR TO ANY STUDY PROCEDURE',
        '#FFC107'
    ),
    (
        'SIGNED INFORMED CONSENT/ASSENT NOT AVAILABLE ON SITE',
        '#FF9800'
    ),
    (
        'WRONG INFORMED CONSENT/ASSENT VERSION SIGNED',
        '#FF5722'
    ),
    (
        'OTHER INFORMED CONSENT/ASSENT DEVIATION',
        '#795548'
    ),
    (
        'NOT DISCONTINUED FROM STUDY TREATMENT',
        '#607D8B'
    ),
    ('NOT WITHDRAWN FROM STUDY', '#F44336'),
    (
        'OTHER DEVIATION OF NOT BEING WITHDRAWN AFTER DEVELOPING WITHDRAWAL CRITERIA',
        '#E91E63'
    ),
    (
        'ACTIVITY LEVEL ABOVE PROTOCOL SPECIFICATION',
        '#9C27B0'
    ),
    (
        'BIOLOGICAL SAMPLE SPECIMEN PROCEDURE',
        '#673AB7'
    ),
    (
        'DECLINED PARTICIPATION IN STUDY PROCEDURE',
        '#3F51B5'
    ),
    ('DIARY PROCEDURE', '#2196F3'),
    (
        'DISCONTINUED PARTICIPATION IN STUDY PROCEDURE',
        '#03A9F4'
    ),
    ('EQUIPMENT PROCEDURE', '#00BCD4'),
    (
        'NON STUDY TREATMENT SUPPLY PROCEDURE',
        '#009688'
    ),
    ('NONCOMPLIANCE WITH STUDY PROCEDURE', '#4CAF50'),
    (
        'POST STUDY TREATMENT OBSERVATION NOT DONE',
        '#8BC34A'
    ),
    (
        'RANDOMIZATION PROCEDURE (E.G. SUBJECT ASSIGNED TO WRONG STRATUM, SUBJECT RANDOMIZED OUT OF ORDER)',
        '#CDDC39'
    ),
    ('STUDY BLINDING/UNBLINDING PROCEDURE', '#FFEB3B'),
    (
        'OTHER DEVIATION FROM STUDY PROCEDURE',
        '#FFC107'
    ),
    ('MISSED VISIT/PHONE CONTACT', '#FF9800'),
    ('OUT OF WINDOW - VISIT/PHONE CONTACT', '#FF5722'),
    ('OTHER VISIT WINDOW DEVIATION', '#795548'),
    (
        'EXPIRED STUDY TREATMENT ADMINISTERED',
        '#607D8B'
    ),
    (
        'STUDY TREATMENT ADMINISTERED WHILE CONTRAINDICATION',
        '#F44336'
    ),
    (
        'STUDY TREATMENT NOT ADMINISTERED PER PROTOCOL',
        '#E91E63'
    ),
    (
        'STUDY TREATMENT NOT AVAILABLE AT SITE FOR ADMINISTRATION',
        '#9C27B0'
    ),
    (
        'STUDY TREATMENT NOT PREPARED AS PER PROTOCOL (E.G. RECONSTITUTION)',
        '#673AB7'
    ),
    (
        'USE OF STUDY TREATMENT IMPACTED BY TEMPERATURE EXCURSION - NOT REPORTED/APPROVED/DISAPPROVED FOR FURTHER USE',
        '#3F51B5'
    ),
    (
        'WRONG STUDY TREATMENT OR ASSIGNMENT ADMINISTERED',
        '#2196F3'
    ),
    (
        'OTHER DEVIATION RELATED TO WRONG STUDY TREATMENT/ADMINISTRATION/DOSE',
        '#03A9F4'
    ),
    ('ERRORS IN DELEGATION LOG COMPLETION', '#00BCD4'),
    ('ERRORS IN SITE FILE COMPLETION', '#009688'),
    (
        'ERRORS IN DOCUMENTATION FOR TRAINING',
        '#4CAF50'
    ),
    (
        'OTHER SITE LEVEL DOCUMENTATION ERRORS',
        '#8BC34A'
    );