INSERT INTO
    dvcat_colour (dvcat, colour)
VALUES
    ('ASSESSMENT OR TIME POINT COMPLETION', '#FF5733'),
    ('ELIGIBILITY CRITERIA NOT MET', '#33FF57'),
    (
        'EXCLUDED MEDICATION, VACCINE OR DEVICE',
        '#5733FF'
    ),
    (
        'FAILURE TO REPORT SAFETY EVENTS PER PROTOCOL',
        '#FFA500'
    ),
    ('INFORMED CONSENT', '#800080'),
    (
        'NOT WITHDRAWN AFTER DEVELOPING WITHDRAWAL CRITERIA',
        '#FFFF00'
    ),
    ('STUDY PROCEDURE', '#008080'),
    ('VISIT COMPLETION', '#FF00FF'),
    (
        'WRONG STUDY TREATMENT/ADMINISTRATION/DOSE',
        '#0000FF'
    ),
    ('SITE LEVEL ERROR', '#FFD700');