CREATE TABLE "data" (
    "data_id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "external_site_id" TEXT NOT NULL,
    "study_id" TEXT NOT NULL,
    "dvspondes" TEXT NOT NULL,
    "file_id" INTEGER,
    "usubjid" TEXT,
    "dventc" DATETIME,
    "dventcviz" TEXT,
    "dvsponsev" TEXT,
    "impor" TEXT,
    "at" TEXT,
    "at_date" DATETIME,
    "domain" TEXT,
    "dvseq" INTEGER,
    "dvref_id" INTEGER,
    "dvendtc" TEXT,
    "adv" TEXT,
    "nonadv" TEXT,
    "dvscat" TEXT,
    "dvstdtc" DATETIME,
    FOREIGN KEY ("study_id") REFERENCES "study"("study_id") ON DELETE CASCADE,
    FOREIGN KEY ("file_id") REFERENCES "file"("file_id") ON DELETE CASCADE
);