CREATE TABLE data_entry (
    entry_id INTEGER PRIMARY KEY AUTOINCREMENT,
    study_id TEXT NOT NULL,
    site_id TEXT NOT NULL,
    dvspondes_id INTEGER,
    usubjid TEXT,
    dventc TEXT,
    dventcviz TEXT,
    dvsponsev TEXT,
    impor INTEGER,
    at TEXT,
    at_date TIMESTAMP,
    domain TEXT,
    dvseq INTEGER,
    dvrefid INTEGER,
    dvendtc TIMESTAMP,
    dvcatid INTEGER,
    dvdecodid INTEGER,
    adv TEXT,
    nonadv TEXT,
    dvs_cat TEXT,
    dvstdtc TIMESTAMP,
    user_id INTEGER,
    is_edited BOOL,
    FOREIGN KEY (dvspondes_id) REFERENCES dvspondes (dvspondes_id) ON DELETE CASCADE ON UPDATE CASCADE
);