import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataTableService {

  public dvcats: string[] = ['FAILURE TO REPORT SAFETY EVENTS PER PROTOCOL',
    'ASSESSMENT OR TIME POINT COMPLETION',
    'ELIGIBILITY CRITERIA NOT MET',
    'WRONG STUDY TREATMENT/ADMINISTRATION/DOSE',
    'INFORMED CONSENT',
    'SITE LEVEL ERROR',
    'EXCLUDED MEDICATION, VACCINE OR DEVICE',
    'NOT WITHDRAWN AFTER DEVELOPING WITHDRAWAL CRITERIA',
    'VISIT COMPLETION',
    'STUDY PROCEDURE'];

  public dvdecods: string[] = [
    "WRONG INFORMED CONSENT/ASSENT VERSION SIGNED",
    "MISSED ASSESMENT - EFFICACY ASSESSMENT",
    "OUT OF WINDOW - ECG",
    "EXPIRED STUDY TREATMENT ADMINISTERED",
    "STUDY TREATMENT NOT AVAILABLE AT SITE FOR ADMINISTRATION",
    "BIOLOGICAL SAMPLE SPECIMEN PROCEDURE",
    "OTHER",
    "INFORMED CONSENT/ASSENT NOT SIGNED AND/OR DATED BY SUBJECT (PARENT/LEGAL REPRESENTATIVE, IF APPLICABLE)",
    "MISSED ASSESMENT - ECG",
    "MISSED ASSESMENT - TREATMENT ADMINISTRATION",
    "STUDY BLINDING/UNBLINDING PROCEDURE",
    "AES OF SPECIAL INTEREST",
    "OTHER EXCLUDED MEDICATION, VACCINE OR DEVICE DEVIATION",
    "DEVICE, EXCLUDED BY THE PROTOCOL, WAS ADMINISTERED",
    "DIARY PROCEDURE",
    "OTHER DEVIATION OF NOT BEING WITHDRAWN AFTER DEVELOPING WITHDRAWAL CRITERIA",
    "WRONG STUDY TREATMENT OR ASSIGNMENT ADMINISTERED",
    "MISSED ASSESMENT - BLOODS CENTRAL",
    "OUT OF WINDOW - EFFICACY ASSESSMENT",
    "INFORMED CONSENT/ASSENT NOT SIGNED AND/OR DATED BY APPROPRIATE SITE STAFF",
    "INCOMPLETE ASSESSMENT",
    "MISSED VISIT/PHONE CONTACT",
    "OUT OF WINDOW - TREATMENT ADMINISTRATION",
    "STUDY TREATMENT NOT ADMINISTERED PER PROTOCOL",
    "ASSESSMENT NOT PROPERLY PERFORMED",
    "ERRORS IN SITE FILE COMPLETION",
    "STUDY TREATMENT ADMINISTERED WHILE CONTRAINDICATION",
    "OUT OF WINDOW - VITAL SIGNS",
    "VACCINE, EXCLUDED BY THE PROTOCOL, WAS ADMINISTERED",
    "OTHER DEVIATION FROM STUDY PROCEDURE",
    "ELIGIBILITY CRITERIA NOT MET",
    "MISSED ASSESMENT - PK COLLECTION",
    "OUT OF WINDOW - VISIT/PHONE CONTACT",
    "MISSED ASSESMENT - BLOODS LOCAL",
    "DISCONTINUED PARTICIPATION IN STUDY PROCEDURE",
    "OUT OF WINDOW - BLOODS LOCAL",
    "OUT OF WINDOW - BIOMARKER COLLECTION OR EXPLORATORY ASSESSMENT",
    "OTHER SITE LEVEL DOCUMENTATION ERRORS",
    "POST STUDY TREATMENT OBSERVATION NOT DONE",
    "MISSED ASSESMENT - BIOMARKER COLLECTION OR EXPLORATORY ASSESSMENT",
    "STUDY TREATMENT NOT PREPARED AS PER PROTOCOL (E.G. RECONSTITUTION)",
    "MEDICATION, EXCLUDED BY THE PROTOCOL, WAS ADMINISTERED",
    "USE OF STUDY TREATMENT IMPACTED BY TEMPERATURE EXCURSION - NOT REPORTED/APPROVED/DISAPPROVED FOR FURTHER USE",
    "DECLINED PARTICIPATION IN STUDY PROCEDURE",
    "NOT WITHDRAWN FROM STUDY",
    "OTHER DEVIATION RELATED TO WRONG STUDY TREATMENT/ADMINISTRATION/DOSE",
    "PREGNANCY",
    "LIVER FUNCTION ABNORMALITIES PER PROTOCOL",
    "ACTIVITY LEVEL ABOVE PROTOCOL SPECIFICATION",
    "NOT DISCONTINUED FROM STUDY TREATMENT",
    "MISSED ASSESSMENT - OTHER",
    "MISSED ASSESMENT - VITAL SIGNS",
    "OUT OF WINDOW - BLOODS CENTRAL",
    "OTHER INFORMED CONSENT/ASSENT DEVIATION",
    "SAE NOT REPORTED WITHIN THE EXPECTED TIME FRAME",
    "FAILURE TO CONFIRM CAUSALITY ASSESSMENT WITHIN THE EXPECTED TIME FRAME",
    "OTHER VISIT WINDOW DEVIATION",
    "ERRORS IN DOCUMENTATION FOR TRAINING",
    "ERRORS IN DELEGATION LOG COMPLETION",
    "RANDOMIZATION PROCEDURE (E.G. SUBJECT ASSIGNED TO WRONG STRATUM, SUBJECT RANDOMIZED OUT OF ORDER)",
    "INFORMED CONSENT/ASSENT NOT SIGNED PRIOR TO ANY STUDY PROCEDURE",
    "EQUIPMENT PROCEDURE",
    "OTHER ASSESSMENT OR TIME POINT WINDOW",
    "OUT OF WINDOW - OTHER",
    "NONCOMPLIANCE WITH STUDY PROCEDURE",
    "NON STUDY TREATMENT SUPPLY PROCEDURE",
    "OUT OF WINDOW - PK COLLECTION",
    "SIGNED INFORMED CONSENT/ASSENT NOT AVAILABLE ON SITE",
    "ASSESSMENT PERFORMED OUT OF ORDER"
  ];

  public static studyIdCellIdentifier = 'studyIdInput';
  public static dvspondesInputCellIdentifier = 'dvspondesInput';
  public static dvcatInputCellIdentifier = 'dvcatInput';
  public static dvdecodInputCellIdentifier = 'dvdecodInput';

  constructor() {}

}
